### ISSUE TITLE
How is the input coarse matrix obtained?

### ISSUE THREAD

**Issue by bluesea0** [PeterZZQ/scDART#1]
Hello, I wonder how the `Input coarse gene activity matrix` is obtained ?   Its shape is `regions*genes`. 

If I use the function `GeneActivity` in Signac, the result `gene.activities` 's shape is `new_genes * cells`.  So how to get the 'region2gene.csv' in your work? Are other R packages used?

Looking forward to your reply. Thx !

**Comment by PeterZZQ** [comment]
Hi,

I just pushed the code that we used to calculate the gene activity matrix. It's essentially the same as `GeneActivity` as our code is modified from the code in Seurat v3. The R script is `calc_coarse_gact/calc_gact.R`. You need to download additional reference files including `Homo_sapiens.GRCh37.82.gtf` for human and `Mus_musculus.GRCm38.84.gtf` for mice. The link is provided in the link file.

**Comment by bluesea0** [comment]
Thanks! It helps a lot.
