### ISSUE TITLE
Error in import

### ISSUE THREAD

**Issue by Chengwei94** [PeterZZQ/scDART#2]
Hi I get this error when trying to use scDart. Maybe it shuold be import scDart.loss as loss?

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/home/chengwei/disco_500t/Projects/scmatchbench/notebooks/test_metrics.ipynb Cell 20 in <cell line: 1>()
----> [1](vscode-notebook-cell://ssh-remote%2B172.20.20.72/home/chengwei/disco_500t/Projects/scmatchbench/notebooks/test_metrics.ipynb#ch0000020vscode-remote?line=0) import scDART

File ~/miniconda3/envs/packages/lib/python3.9/site-packages/scDART/__init__.py:4, in <module>
      1 "scDART"
      3 # read in main class
----> 4 from .scDART import scDART

File ~/miniconda3/envs/packages/lib/python3.9/site-packages/scDART/scDART.py:15, in <module>
     13 import scDART.dataset as dataset
     14 import scDART.model as model
---> 15 import scDART.train as train
     16 import scDART.utils as utils
     17 import scDART.post_align as palign

File ~/miniconda3/envs/packages/lib/python3.9/site-packages/scDART/train.py:5, in <module>
      3 import torch.nn.functional as F 
      4 import numpy as np
----> 5 import loss
      6 from torch.autograd import Variable
      7 from torch import autograd

ModuleNotFoundError: No module named 'loss'

**Comment by PeterZZQ** [comment]
Hi, the bug should be fixed now in the latest version.
