### ISSUE TITLE
module 'scDART' has no attribute 'scDART'

### ISSUE THREAD

**Issue by sshen82** [PeterZZQ/scDART#5]
Hi Peter,
I met another problem when running your example. One is that when running

import scDART.utils as utils

It shows the error "No module named 'scDART.utils'".

The second is that when running:

scDART_op = scDART.scDART(n_epochs = n_epochs, latent_dim = latent_dim, \
        ts = ts, use_anchor = use_anchor, use_potential = use_potential, k = 10, \
        reg_d = 1, reg_g = 1, reg_mmd = 1, l_dist_type = 'kl', seed = seeds[0],\
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu'))

It shows:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'scDART' has no attribute 'scDART'

The scDART should be successfully installed, since I can do "import scDART". What other possible problems do you think there are?

Yours sincerely,
Siqi Shen

**Comment by PeterZZQ** [comment]
Hi,

I just tested scDART using a ubuntu system on docker and its working, here is the Docker file that I used
```
FROM ubuntu:20.04.
RUN apt-get -y update
RUN apt-get -y install git python3-pip
RUN cd / \
&& git clone https://github.com/PeterZZQ/scDART.git\
&& cd scDART\
&& pip3 install .\
&& pip3 install torch\
&& cd ..\
&& mkdir -p /test_scdart/outputs

COPY test_run.py /test_scdart/
CMD cd /test_scdart\
&& python3 test_run.py
```
In the test script `test_run.py`, I called the functions in `scDART.scDART` and `scDART.utils`. Maybe it's the version issue. Please try uninstalling your current scDART. Then you can pull the newest version of the code from GitHub and test again. Let me know if there is still any issue.

**Comment by sshen82** [comment]
It works. Thanks!

**Comment by HelloWorldLTY** [comment]
Hi, I also meet this problem, and uninstall operation did not work for me. Instead, I tried to delete the scDART folder after pip install and it works. I think the reference priority of local scDART is higher than scDART package in the pip environment, so maybe this is also a solution.
