### ISSUE TITLE
Saving gene activity matrix

### ISSUE THREAD

**Issue by sshen82** [PeterZZQ/scDART#6]
Hi Peter,
Sorry for sending a lot of questions! I hope this is the last one, but is it possible to obtain the updated gene activity matrix from the algorithm? I feel that it is more important for me comparing to the embeddings.

Yours sincerely,
Siqi Shen

**Comment by PeterZZQ** [comment]
Hi Siqi, our method learns a nonlinear gene activity function that predicts scRNA-seq from scATAC-seq data. It's hard to extract the updated gene activity matrix from our model given the nonlinearity of the gene activity function. It is a good point and it is something that we should be working on for the next step.
